// Command strip-redfish-routes derives the set of Redfish endpoints with a
// real implementation from the generated service file, so the Redfish server
// can strip every other route from its route table. The OpenAPI generator
// emits one APIService method per operation; unimplemented ones keep a stub
// body that returns http.StatusNotImplemented. Registering all ~4000
// generated routes makes gorilla/mux compile every pattern into a regexp
// that stays live for the process lifetime (~50MB heap per agent pod,
// kubevirtbmc/kubevirtbmc#264).
//
// Usage (via go:generate in pkg/redfish):
//
//	go run ./strip-redfish-routes -input api_service.go -output implemented_routes_gen.go
package main

import (
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"sort"
	"strings"
)

func main() {
	input := flag.String("input", "api_service.go", "generated Redfish service implementation to scan")
	output := flag.String("output", "implemented_routes_gen.go", "file to write the implemented method set to")
	flag.Parse()

	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, *input, nil, 0)
	if err != nil {
		fmt.Fprintf(os.Stderr, "strip-redfish-routes: parse %s: %v\n", *input, err)
		os.Exit(1)
	}

	implemented := make([]string, 0, len(f.Decls))
	for _, decl := range f.Decls {
		fn, ok := decl.(*ast.FuncDecl)
		if !ok || !isAPIServiceMethod(fn) || isNotImplementedStub(fn) {
			continue
		}
		implemented = append(implemented, fn.Name.Name)
	}
	sort.Strings(implemented)

	var b strings.Builder
	b.WriteString("// Code generated by strip-redfish-routes (pkg/redfish/strip-redfish-routes); DO NOT EDIT.\n")
	b.WriteString("\npackage redfish\n\n")
	b.WriteString("// implementedMethods holds the APIService methods with a real\n")
	b.WriteString("// implementation, i.e. those not returning the generated 501 stub.\n")
	b.WriteString("// Generated route names match these method names, plus optional _N\n")
	b.WriteString("// suffixes for alias paths of the same operation.\n")
	b.WriteString("var implementedMethods = map[string]bool{\n")
	for _, name := range implemented {
		fmt.Fprintf(&b, "\t%q: true,\n", name)
	}
	b.WriteString("}\n")

	src, err := format.Source([]byte(b.String()))
	if err != nil {
		fmt.Fprintf(os.Stderr, "strip-redfish-routes: format output: %v\n", err)
		os.Exit(1)
	}
	if err := os.WriteFile(*output, src, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "strip-redfish-routes: write %s: %v\n", *output, err)
		os.Exit(1)
	}
	fmt.Fprintf(os.Stderr, "strip-redfish-routes: %d implemented methods -> %s\n", len(implemented), *output)
}

func isAPIServiceMethod(fn *ast.FuncDecl) bool {
	if fn.Recv == nil || len(fn.Recv.List) != 1 {
		return false
	}
	star, ok := fn.Recv.List[0].Type.(*ast.StarExpr)
	if !ok {
		return false
	}
	ident, ok := star.X.(*ast.Ident)
	return ok && ident.Name == "APIService"
}

// isNotImplementedStub reports whether the method body references
// http.StatusNotImplemented. Generated stubs always do; a real implementation
// must not, otherwise it would be dropped from the route table. Only the
// net/http constant counts: a real implementation may legitimately reference
// some other StatusNotImplemented constant.
func isNotImplementedStub(fn *ast.FuncDecl) bool {
	stub := false
	ast.Inspect(fn.Body, func(n ast.Node) bool {
		if stub {
			return false
		}
		if sel, ok := n.(*ast.SelectorExpr); ok {
			if x, ok := sel.X.(*ast.Ident); ok && x.Name == "http" && sel.Sel.Name == "StatusNotImplemented" {
				stub = true
			}
		}
		return !stub
	})
	return stub
}
