// Code generated by strip-redfish-routes (pkg/redfish/strip-redfish-routes); DO NOT EDIT.

package redfish

// implementedMethods holds the APIService methods with a real
// implementation, i.e. those not returning the generated 501 stub.
// Generated route names match these method names, plus optional _N
// suffixes for alias paths of the same operation.
var implementedMethods = map[string]bool{
	"RedfishV1Get":         true,
	"RedfishV1ManagersGet": true,
	"RedfishV1ManagersManagerIdActionsManagerResetPost":                                      true,
	"RedfishV1ManagersManagerIdGet":                                                          true,
	"RedfishV1ManagersManagerIdVirtualMediaGet":                                              true,
	"RedfishV1ManagersManagerIdVirtualMediaVirtualMediaIdActionsVirtualMediaEjectMediaPost":  true,
	"RedfishV1ManagersManagerIdVirtualMediaVirtualMediaIdActionsVirtualMediaInsertMediaPost": true,
	"RedfishV1ManagersManagerIdVirtualMediaVirtualMediaIdGet":                                true,
	"RedfishV1SessionServiceGet":                                                             true,
	"RedfishV1SessionServiceSessionsPost":                                                    true,
	"RedfishV1SessionServiceSessionsSessionIdDelete":                                         true,
	"RedfishV1SessionServiceSessionsSessionIdGet":                                            true,
	"RedfishV1SystemsComputerSystemIdActionsComputerSystemResetPost":                         true,
	"RedfishV1SystemsComputerSystemIdActionsComputerSystemSetDefaultBootOrderPost":           true,
	"RedfishV1SystemsComputerSystemIdGet":                                                    true,
	"RedfishV1SystemsComputerSystemIdOperatingSystemGet":                                     true,
	"RedfishV1SystemsComputerSystemIdPatch":                                                  true,
	"RedfishV1SystemsGet":                                                                    true,
}

// serviceRootLinks maps each implemented ServiceRoot top-level link
// property to its URI, so the service root only advertises links a
// client can actually dereference (DSP0266 hypermedia discovery).
// Derived from the OdataV4IdRef properties of the generated ServiceRoot
// model, gated on the backing collection GET being implemented.
var serviceRootLinks = map[string]string{
	"Managers":       "/redfish/v1/Managers",
	"SessionService": "/redfish/v1/SessionService",
	"Systems":        "/redfish/v1/Systems",
}
